version: '3'
services:
  dash:
    build: ./src
    container_name: dash-app
    restart: always
    networks:
      - network


    volumes:
      - .src//test_task:/app

    ports:
      - "8050:8050"


networks:
  network:
    driver: bridge